import type { Metadata } from "next";
import ".././globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import { Home, Book, FileText, Clipboard } from 'lucide-react'; // Import Lucide Icons
import { MenuItem } from "@/types/MenuItem";
import { ToasterProvider } from "@/components/Toaster";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menuItems: MenuItem[] = [
  { name: 'Dashboard', route: '/employee', icon: <Home size={24} /> },
  { name: 'Learnings & Events', route: '/employee/learnings', icon: <Book size={24} /> },
  { name: 'New Request', route: '/employee/new-request', icon: <FileText size={24} /> },
  { name: 'KRA’s & Goals', route: 'https://winpr.azurewebsites.net/MyGoals', icon: <Clipboard size={24} />, target: "_blank" },
];

export default function EmployeeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Sidebar menuItems={menuItems}>
      <ToasterProvider>
        {children}
      </ToasterProvider>
    </Sidebar>
  );
}
