import type { Metadata } from "next";
import ".././globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import { MenuItem } from "@/types/MenuItem";
import {
  LayoutDashboard,
  ClipboardList,
  BookOpen,
  BarChart2,
  BookUser,
  Speech
} from 'lucide-react'

const menuItems: MenuItem[] = [
  {
    name: 'Dashboard',
    route: '/l&d',
    icon: <LayoutDashboard size={24} />
  },
  {
    name: 'Training Requests',
    route: '/l&d/training-requests',
    icon: <ClipboardList size={24} />
  },
  {
    name: 'Brown Bag Requests',
    route: '/l&d/brown-bag-requests',
    icon: <Speech size={24} />
  },
  {
    name: 'Reports & Analytics',
    route: '/l&d/analytics',
    icon: <BarChart2 size={24} />
  },
  {
    name: 'Add Course',
    route: '/l&d/add-course',
    icon: <BookUser size={24} />
  },
  {
    name: 'Course Catalog',
    route: '/l&d/courses',
    icon: <BookOpen size={24} />
  },

]





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Sidebar menuItems={menuItems}>
      {children}
    </Sidebar>
  );
}
